name: Configurar Node.js + PNPM e instalar dependencias
description: |
  Esta es una GitHub Action compuesta que:
  - Configura el gestor de paquetes pnpm
  - Configura el entorno de Node.js
  - Instala las dependencias del proyecto utilizando caché

inputs:
  node-version:
    description: "Versión explícita de Node. De lo contrario, utilizará como alternativa 'engines.node' del 'package.json'"

runs:
  using: composite

  steps:
    - name: Instalar pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5

    - name: Configurar Node.js (vía input)
      if: ${{ inputs.node-version }}
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
        registry-url: "https://registry.npmjs.org"

    - name: Configurar Node.js (vía engines de package.json)
      if: ${{ !inputs.node-version }}
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: "package.json"
        cache: "pnpm"
        registry-url: "https://registry.npmjs.org"

    - name: Instalar dependencias
      shell: bash
      run: pnpm install --frozen-lockfile
