version: 2
updates:
  # Mantener actualizadas las dependencias para npm
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  # Mantener actualizadas las dependencias para GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    commit-message:
      prefix: "ci(deps)"
      prefix-development: "ci(deps-dev)"
    cooldown:
      default-days: 7
